In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df.shape

(1338, 9)

In [4]:
df.columns

Index(['age', 'sex', 'bmi', 'steps', 'children', 'smoker', 'region', 'charges',
       'insuranceclaim'],
      dtype='object')

In [5]:
df.head()

,age,sex,bmi,steps,children,smoker,region,charges,insuranceclaim
0,19,0,27.900,3009,0,1,3,16884.92400,1
1,18,1,33.770,3008,1,0,2,1725.55230,1
2,28,1,33.000,3009,3,0,2,4449.46200,0
3,33,1,22.705,10009,0,0,1,21984.47061,0
4,32,1,28.880,8010,0,0,1,3866.85520,1

In [6]:
# checking if null values exist in the dataset
df[df.isnull().any(axis=1)].head()

Empty DataFrame
Columns: [age, sex, bmi, steps, children, smoker, region, charges, insuranceclaim]
Index: []

In [7]:
# Split the train data in test and train
X = df.drop('insuranceclaim', axis=1)
y = df['insuranceclaim']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=324)

In [8]:
#fitting decision tree model on the data
insurance_classifier = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
insurance_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [9]:
y_predicted = insurance_classifier.predict(X_test)

In [10]:
#checking test accuracy
accuracy_score(y_test,y_predicted)*100

89.92537313432835

In [11]:
confusion_matrix(y_test, y_predicted)

array([[ 98,   6],
       [ 21, 143]], dtype=int64)